// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sgo/options.proto

package sgoproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_sgo_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "sgo.aggregate_root",
		Tag:           "varint,50001,opt,name=aggregate_root",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "sgo.value_object",
		Tag:           "varint,50002,opt,name=value_object",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "sgo.domain_event",
		Tag:           "varint,50003,opt,name=domain_event",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "sgo.command",
		Tag:           "varint,50001,opt,name=command",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "sgo.query",
		Tag:           "varint,50002,opt,name=query",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50003,
		Name:          "sgo.repository_query",
		Tag:           "varint,50003,opt,name=repository_query",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50004,
		Name:          "sgo.hide_route",
		Tag:           "varint,50004,opt,name=hide_route",
		Filename:      "sgo/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "sgo.base_path",
		Tag:           "bytes,50001,opt,name=base_path",
		Filename:      "sgo/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool aggregate_root = 50001;
	E_AggregateRoot = &file_sgo_options_proto_extTypes[0]
	// optional bool value_object = 50002;
	E_ValueObject = &file_sgo_options_proto_extTypes[1]
	// optional bool domain_event = 50003;
	E_DomainEvent = &file_sgo_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool command = 50001;
	E_Command = &file_sgo_options_proto_extTypes[3]
	// optional bool query = 50002;
	E_Query = &file_sgo_options_proto_extTypes[4]
	// optional bool repository_query = 50003;
	E_RepositoryQuery = &file_sgo_options_proto_extTypes[5]
	// optional bool hide_route = 50004;
	E_HideRoute = &file_sgo_options_proto_extTypes[6]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string base_path = 50001;
	E_BasePath = &file_sgo_options_proto_extTypes[7]
)

var File_sgo_options_proto protoreflect.FileDescriptor

const file_sgo_options_proto_rawDesc = "" +
	"\n" +
	"\x11sgo/options.proto\x12\x03sgo\x1a google/protobuf/descriptor.proto:H\n" +
	"\x0eaggregate_root\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\bR\raggregateRoot:D\n" +
	"\fvalue_object\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\bR\vvalueObject:D\n" +
	"\fdomain_event\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\bR\vdomainEvent::\n" +
	"\acommand\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\acommand:6\n" +
	"\x05query\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\bR\x05query:K\n" +
	"\x10repository_query\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\bR\x0frepositoryQuery:?\n" +
	"\n" +
	"hide_route\x12\x1e.google.protobuf.MethodOptions\x18Ԇ\x03 \x01(\bR\thideRoute:>\n" +
	"\tbase_path\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x01(\tR\bbasePathB/Z-github.com/wahyurudiyan/sunny-go/pkg/sgoprotob\x06proto3"

var file_sgo_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_sgo_options_proto_depIdxs = []int32{
	0, // 0: sgo.aggregate_root:extendee -> google.protobuf.MessageOptions
	0, // 1: sgo.value_object:extendee -> google.protobuf.MessageOptions
	0, // 2: sgo.domain_event:extendee -> google.protobuf.MessageOptions
	1, // 3: sgo.command:extendee -> google.protobuf.MethodOptions
	1, // 4: sgo.query:extendee -> google.protobuf.MethodOptions
	1, // 5: sgo.repository_query:extendee -> google.protobuf.MethodOptions
	1, // 6: sgo.hide_route:extendee -> google.protobuf.MethodOptions
	2, // 7: sgo.base_path:extendee -> google.protobuf.ServiceOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	0, // [0:8] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sgo_options_proto_init() }
func file_sgo_options_proto_init() {
	if File_sgo_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgo_options_proto_rawDesc), len(file_sgo_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_sgo_options_proto_goTypes,
		DependencyIndexes: file_sgo_options_proto_depIdxs,
		ExtensionInfos:    file_sgo_options_proto_extTypes,
	}.Build()
	File_sgo_options_proto = out.File
	file_sgo_options_proto_goTypes = nil
	file_sgo_options_proto_depIdxs = nil
}
