package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const version = "v1.0.0"

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")
	flag.Parse()

	if *showVersion {
		fmt.Printf("protoc-gen-go-http %v\n", version)
		return
	}

	var flags flag.FlagSet
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateHTTPFile(gen, f)
		}
		return nil
	})
}

func generateHTTPFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// 	protoc-gen-go-http ", version)
	g.P("// 	protoc              ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()

	// Package declaration
	g.P("package ", file.GoPackageName)
	g.P()

	// Imports
	generateImports(g)

	// Generate for each service
	for _, service := range file.Services {
		generateHTTPService(g, service)
	}
}

func generateImports(g *protogen.GeneratedFile) {
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"encoding/json"`)
	g.P(`	"fmt"`)
	g.P(`	"io"`)
	g.P(`	"net/http"`)
	g.P(`	"net/url"`)
	g.P(`	"strconv"`)
	g.P(`	"strings"`)
	g.P()
	g.P(`	"github.com/gorilla/mux"`)
	g.P(`	"google.golang.org/grpc/codes"`)
	g.P(`	"google.golang.org/grpc/status"`)
	g.P(`	"google.golang.org/protobuf/encoding/protojson"`)
	g.P(")")
	g.P()
}

func generateHTTPService(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName

	// HTTP Server interface
	g.P("// ", serviceName, "HTTPServer is the server API for ", serviceName, " service.")
	g.P("type ", serviceName, "HTTPServer interface {")
	for _, method := range service.Methods {
		g.P("	", method.GoName, "(context.Context, *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error)")
	}
	g.P("}")
	g.P()

	// HTTP Client interface
	g.P("// ", serviceName, "HTTPClient is the client API for ", serviceName, " service.")
	g.P("type ", serviceName, "HTTPClient interface {")
	for _, method := range service.Methods {
		g.P("	", method.GoName, "(ctx context.Context, req *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error)")
	}
	g.P("}")
	g.P()

	// Server registration function
	generateServerRegistration(g, service)

	// Client implementation
	generateHTTPClient(g, service)

	// Error mapping
	generateErrorMapping(g)
}

func generateServerRegistration(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName

	g.P("// Register", serviceName, "HTTPServer registers the http handlers for service ", serviceName, " to \"mux\".")
	g.P("func Register", serviceName, "HTTPServer(mux *mux.Router, srv ", serviceName, "HTTPServer) {")

	for _, method := range service.Methods {
		httpRule := getHTTPRule(method)
		if httpRule != nil {
			generateMethodHandler(g, service, method, httpRule)
		}
	}

	g.P("}")
	g.P()
}

func generateMethodHandler(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, rule *HTTPRule) {
	methodName := method.GoName
	inputType := method.Input.GoIdent

	// Handler function
	handlerName := fmt.Sprintf("_%s_%s_HTTP_Handler", service.GoName, methodName)

	g.P("	mux.HandleFunc(\"", rule.Path, "\", ", handlerName, "(srv)).Methods(\"", rule.Method, "\")")

	// Generate the actual handler function
	g.P()
	g.P("func ", handlerName, "(srv ", service.GoName, "HTTPServer) http.HandlerFunc {")
	g.P("	return func(w http.ResponseWriter, r *http.Request) {")
	g.P("		var req ", inputType)

	if rule.Method == "GET" || rule.Method == "DELETE" {
		// Handle path parameters and query parameters
		generateGetRequestBinding(g, method, rule)
	} else {
		// Handle request body for POST/PUT
		generatePostRequestBinding(g, method)
	}

	g.P()
	g.P("		resp, err := srv.", methodName, "(r.Context(), &req)")
	g.P("		if err != nil {")
	g.P("			httpErr := grpcErrorToHTTP(err)")
	g.P("			http.Error(w, httpErr.Message, httpErr.Code)")
	g.P("			return")
	g.P("		}")
	g.P()
	g.P("		w.Header().Set(\"Content-Type\", \"application/json\")")
	g.P("		if err := json.NewEncoder(w).Encode(resp); err != nil {")
	g.P("			http.Error(w, \"Failed to encode response\", http.StatusInternalServerError)")
	g.P("		}")
	g.P("	}")
	g.P("}")
	g.P()
}

func generateGetRequestBinding(g *protogen.GeneratedFile, method *protogen.Method, rule *HTTPRule) {
	g.P("		// Extract path parameters")
	g.P("		vars := mux.Vars(r)")
	g.P("		if id, ok := vars[\"id\"]; ok {")
	g.P("			req.Id = id")
	g.P("		}")
	g.P()
	g.P("		// Extract query parameters")
	g.P("		query := r.URL.Query()")
	g.P("		if page := query.Get(\"page\"); page != \"\" {")
	g.P("			if p, err := strconv.ParseInt(page, 10, 32); err == nil {")
	g.P("				req.Page = int32(p)")
	g.P("			}")
	g.P("		}")
	g.P("		if pageSize := query.Get(\"page_size\"); pageSize != \"\"{")
	g.P("			if ps, err := strconv.ParseInt(pageSize, 10, 32); err == nil {")
	g.P("				req.PageSize = int32(ps)")
	g.P("			}")
	g.P("		}")
}

func generatePostRequestBinding(g *protogen.GeneratedFile, method *protogen.Method) {
	g.P("		// Extract path parameters")
	g.P("		vars := mux.Vars(r)")
	g.P("		if id, ok := vars[\"id\"]; ok {")
	g.P("			req.Id = id")
	g.P("		}")
	g.P()
	g.P("		// Parse request body")
	g.P("		body, err := io.ReadAll(r.Body)")
	g.P("		if err != nil {")
	g.P("			http.Error(w, \"Failed to read request body\", http.StatusBadRequest)")
	g.P("			return")
	g.P("		}")
	g.P()
	g.P("		if len(body) > 0 {")
	g.P("			if err := protojson.Unmarshal(body, &req); err != nil {")
	g.P("				http.Error(w, \"Failed to parse request body\", http.StatusBadRequest)")
	g.P("				return")
	g.P("			}")
	g.P("		}")
}

func generateHTTPClient(g *protogen.GeneratedFile, service *protogen.Service) {
	serviceName := service.GoName

	// Client struct
	g.P("type ", serviceName, "HTTPClientImpl struct {")
	g.P("	baseURL string")
	g.P("	client  *http.Client")
	g.P("}")
	g.P()

	// Constructor
	g.P("// New", serviceName, "HTTPClient creates a new HTTP client for ", serviceName, " service.")
	g.P("func New", serviceName, "HTTPClient(baseURL string) ", serviceName, "HTTPClient {")
	g.P("	return &", serviceName, "HTTPClientImpl{")
	g.P("		baseURL: strings.TrimRight(baseURL, \"/\"),")
	g.P("		client:  &http.Client{},")
	g.P("	}")
	g.P("}")
	g.P()

	// Method implementations
	for _, method := range service.Methods {
		generateHTTPClientMethod(g, service, method)
	}
}

func generateHTTPClientMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	serviceName := service.GoName
	methodName := method.GoName
	inputType := method.Input.GoIdent
	outputType := method.Output.GoIdent

	rule := getHTTPRule(method)
	if rule == nil {
		return
	}

	g.P("func (c *", serviceName, "HTTPClientImpl) ", methodName, "(ctx context.Context, req *", inputType, ") (*", outputType, ", error) {")

	// Build URL
	if rule.Method == "GET" || rule.Method == "DELETE" {
		g.P("	url := c.baseURL + \"", rule.Path, "\"")
		g.P("	if req.Id != \"\" {")
		g.P("		url = strings.Replace(url, \"{id}\", req.Id, 1)")
		g.P("	}")
		if rule.Method == "GET" {
			g.P("	// Add query parameters")
			g.P("	params := url.Values{}")
			g.P("	if req.Page > 0 {")
			g.P("		params.Set(\"page\", strconv.Itoa(int(req.Page)))")
			g.P("	}")
			g.P("	if req.PageSize > 0 {")
			g.P("		params.Set(\"page_size\", strconv.Itoa(int(req.PageSize)))")
			g.P("	}")
			g.P("	if len(params) > 0 {")
			g.P("		url += \"?\" + params.Encode()")
			g.P("	}")
		}
		g.P("	httpReq, err := http.NewRequestWithContext(ctx, \"", rule.Method, "\", url, nil)")
	} else {
		g.P("	url := c.baseURL + \"", rule.Path, "\"")
		g.P("	if req.Id != \"\" {")
		g.P("		url = strings.Replace(url, \"{id}\", req.Id, 1)")
		g.P("	}")
		g.P("	body, err := protojson.Marshal(req)")
		g.P("	if err != nil {")
		g.P("		return nil, fmt.Errorf(\"failed to marshal request: %w\", err)")
		g.P("	}")
		g.P("	httpReq, err := http.NewRequestWithContext(ctx, \"", rule.Method, "\", url, strings.NewReader(string(body)))")
		g.P("	if err == nil {")
		g.P("		httpReq.Header.Set(\"Content-Type\", \"application/json\")")
		g.P("	}")
	}

	g.P("	if err != nil {")
	g.P("		return nil, fmt.Errorf(\"failed to create request: %w\", err)")
	g.P("	}")
	g.P()
	g.P("	resp, err := c.client.Do(httpReq)")
	g.P("	if err != nil {")
	g.P("		return nil, fmt.Errorf(\"failed to perform request: %w\", err)")
	g.P("	}")
	g.P("	defer resp.Body.Close()")
	g.P()
	g.P("	if resp.StatusCode >= 400 {")
	g.P("		body, _ := io.ReadAll(resp.Body)")
	g.P("		return nil, fmt.Errorf(\"HTTP %d: %s\", resp.StatusCode, string(body))")
	g.P("	}")
	g.P()
	g.P("	respBody, err := io.ReadAll(resp.Body)")
	g.P("	if err != nil {")
	g.P("		return nil, fmt.Errorf(\"failed to read response: %w\", err)")
	g.P("	}")
	g.P()
	g.P("	var result ", outputType)
	g.P("	if err := protojson.Unmarshal(respBody, &result); err != nil {")
	g.P("		return nil, fmt.Errorf(\"failed to unmarshal response: %w\", err)")
	g.P("	}")
	g.P()
	g.P("	return &result, nil")
	g.P("}")
	g.P()
}

func generateErrorMapping(g *protogen.GeneratedFile) {
	g.P("// HTTPError represents an HTTP error")
	g.P("type HTTPError struct {")
	g.P("	Code    int")
	g.P("	Message string")
	g.P("}")
	g.P()
	g.P("// grpcErrorToHTTP converts gRPC errors to HTTP errors")
	g.P("func grpcErrorToHTTP(err error) *HTTPError {")
	g.P("	if err == nil {")
	g.P("		return nil")
	g.P("	}")
	g.P()
	g.P("	st, ok := status.FromError(err)")
	g.P("	if !ok {")
	g.P("		return &HTTPError{Code: http.StatusInternalServerError, Message: err.Error()}")
	g.P("	}")
	g.P()
	g.P("	switch st.Code() {")
	g.P("	case codes.OK:")
	g.P("		return &HTTPError{Code: http.StatusOK, Message: st.Message()}")
	g.P("	case codes.InvalidArgument:")
	g.P("		return &HTTPError{Code: http.StatusBadRequest, Message: st.Message()}")
	g.P("	case codes.NotFound:")
	g.P("		return &HTTPError{Code: http.StatusNotFound, Message: st.Message()}")
	g.P("	case codes.AlreadyExists:")
	g.P("		return &HTTPError{Code: http.StatusConflict, Message: st.Message()}")
	g.P("	case codes.PermissionDenied:")
	g.P("		return &HTTPError{Code: http.StatusForbidden, Message: st.Message()}")
	g.P("	case codes.Unauthenticated:")
	g.P("		return &HTTPError{Code: http.StatusUnauthorized, Message: st.Message()}")
	g.P("	case codes.ResourceExhausted:")
	g.P("		return &HTTPError{Code: http.StatusTooManyRequests, Message: st.Message()}")
	g.P("	case codes.FailedPrecondition:")
	g.P("		return &HTTPError{Code: http.StatusPreconditionFailed, Message: st.Message()}")
	g.P("	case codes.Aborted:")
	g.P("		return &HTTPError{Code: http.StatusConflict, Message: st.Message()}")
	g.P("	case codes.OutOfRange:")
	g.P("		return &HTTPError{Code: http.StatusBadRequest, Message: st.Message()}")
	g.P("	case codes.Unimplemented:")
	g.P("		return &HTTPError{Code: http.StatusNotImplemented, Message: st.Message()}")
	g.P("	case codes.Internal:")
	g.P("		return &HTTPError{Code: http.StatusInternalServerError, Message: st.Message()}")
	g.P("	case codes.Unavailable:")
	g.P("		return &HTTPError{Code: http.StatusServiceUnavailable, Message: st.Message()}")
	g.P("	case codes.DataLoss:")
	g.P("		return &HTTPError{Code: http.StatusInternalServerError, Message: st.Message()}")
	g.P("	default:")
	g.P("		return &HTTPError{Code: http.StatusInternalServerError, Message: st.Message()}")
	g.P("	}")
	g.P("}")
	g.P()
}

// HTTPRule represents HTTP routing information
type HTTPRule struct {
	Method string
	Path   string
}

// getHTTPRule extracts HTTP rule from method options
func getHTTPRule(method *protogen.Method) *HTTPRule {
	// This is a simplified implementation
	// In a real implementation, you would parse google.api.http options

	methodName := strings.ToLower(method.GoName)
	serviceName := strings.ToLower(method.Parent.GoName)

	// Remove "Service" suffix if present
	if strings.HasSuffix(serviceName, "service") {
		serviceName = serviceName[:len(serviceName)-7]
	}

	switch {
	case strings.HasPrefix(methodName, "create"):
		return &HTTPRule{Method: "POST", Path: fmt.Sprintf("/api/v1/%ss", serviceName)}
	case strings.HasPrefix(methodName, "get"):
		return &HTTPRule{Method: "GET", Path: fmt.Sprintf("/api/v1/%ss/{id}", serviceName)}
	case strings.HasPrefix(methodName, "list"):
		return &HTTPRule{Method: "GET", Path: fmt.Sprintf("/api/v1/%ss", serviceName)}
	case strings.HasPrefix(methodName, "update"):
		return &HTTPRule{Method: "PUT", Path: fmt.Sprintf("/api/v1/%ss/{id}", serviceName)}
	case strings.HasPrefix(methodName, "delete"):
		return &HTTPRule{Method: "DELETE", Path: fmt.Sprintf("/api/v1/%ss/{id}", serviceName)}
	default:
		return &HTTPRule{Method: "POST", Path: fmt.Sprintf("/api/v1/%ss/%s", serviceName, methodName)}
	}
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}
