package generate

import (
	"fmt"
	"path/filepath"
)

// generateAPIFiles generates API files using simple templates
func generateAPIFiles(serviceName, protoPath, apiDir string) error {
	fmt.Printf("⚡ Generating API files for %s...\n", serviceName)

	config := &GenerateConfig{
		ServiceName: serviceName,
	}

	// Generate the three files using templates from api_templates.go
	files := map[string]string{
		serviceName + ".pb.go":      pbGoTemplate,
		serviceName + "_grpc.pb.go": grpcGoTemplate,
		serviceName + "_http.pb.go": httpGoTemplate,
	}

	for fileName, templateContent := range files {
		filePath := filepath.Join(apiDir, fileName)
		if err := generateFileFromTemplate(filePath, templateContent, config); err != nil {
			return fmt.Errorf("failed to generate %s: %w", fileName, err)
		}
	}

	fmt.Printf("✅ Generated API files:\n")
	fmt.Printf("   - %s.pb.go (message types and proto definitions)\n", serviceName)
	fmt.Printf("   - %s_grpc.pb.go (gRPC server/client interfaces)\n", serviceName)
	fmt.Printf("   - %s_http.pb.go (HTTP server/client with Gorilla Mux routing)\n", serviceName)

	return nil
}

// Template definitions for API generation
const pbGoTemplate = `// Code generated by sunny-go. DO NOT EDIT.

package {{.ServiceName}}

// {{.ServiceName | title}} represents a {{.ServiceName}} entity
type {{.ServiceName | title}} struct {
	Id          string ` + "`json:\"id,omitempty\"`" + `
	Name        string ` + "`json:\"name,omitempty\"`" + `
	Description string ` + "`json:\"description,omitempty\"`" + `
}

// Create{{.ServiceName | title}}Request represents the request to create a {{.ServiceName}}
type Create{{.ServiceName | title}}Request struct {
	Name        string ` + "`json:\"name,omitempty\"`" + `
	Description string ` + "`json:\"description,omitempty\"`" + `
}

// Get{{.ServiceName | title}}Request represents the request to get a {{.ServiceName}}
type Get{{.ServiceName | title}}Request struct {
	Id string ` + "`json:\"id,omitempty\"`" + `
}

// List{{.ServiceName | title}}sRequest represents the request to list {{.ServiceName}}s
type List{{.ServiceName | title}}sRequest struct {
	Page     int32 ` + "`json:\"page,omitempty\"`" + `
	PageSize int32 ` + "`json:\"page_size,omitempty\"`" + `
}

// Update{{.ServiceName | title}}Request represents the request to update a {{.ServiceName}}
type Update{{.ServiceName | title}}Request struct {
	Id          string ` + "`json:\"id,omitempty\"`" + `
	Name        string ` + "`json:\"name,omitempty\"`" + `
	Description string ` + "`json:\"description,omitempty\"`" + `
}

// Delete{{.ServiceName | title}}Request represents the request to delete a {{.ServiceName}}
type Delete{{.ServiceName | title}}Request struct {
	Id string ` + "`json:\"id,omitempty\"`" + `
}

// {{.ServiceName | title}}Response represents the response containing a {{.ServiceName}}
type {{.ServiceName | title}}Response struct {
	{{.ServiceName | title}} *{{.ServiceName | title}} ` + "`json:\"{{.ServiceName}},omitempty\"`" + `
}

// List{{.ServiceName | title}}sResponse represents the response containing a list of {{.ServiceName}}s
type List{{.ServiceName | title}}sResponse struct {
	{{.ServiceName | title}}s []*{{.ServiceName | title}} ` + "`json:\"{{.ServiceName}}s,omitempty\"`" + `
	Total    int32                  ` + "`json:\"total,omitempty\"`" + `
	Page     int32                  ` + "`json:\"page,omitempty\"`" + `
	PageSize int32                  ` + "`json:\"page_size,omitempty\"`" + `
}

// Empty represents an empty response
type Empty struct{}`

const grpcGoTemplate = `// Code generated by sunny-go. DO NOT EDIT.

package {{.ServiceName}}

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// {{.ServiceName | title}}ServiceServer is the server API for {{.ServiceName | title}}Service service.
type {{.ServiceName | title}}ServiceServer interface {
	Create{{.ServiceName | title}}(context.Context, *Create{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	Get{{.ServiceName | title}}(context.Context, *Get{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	List{{.ServiceName | title}}s(context.Context, *List{{.ServiceName | title}}sRequest) (*List{{.ServiceName | title}}sResponse, error)
	Update{{.ServiceName | title}}(context.Context, *Update{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	Delete{{.ServiceName | title}}(context.Context, *Delete{{.ServiceName | title}}Request) (*Empty, error)
}

// {{.ServiceName | title}}ServiceClient is the client API for {{.ServiceName | title}}Service service.
type {{.ServiceName | title}}ServiceClient interface {
	Create{{.ServiceName | title}}(ctx context.Context, in *Create{{.ServiceName | title}}Request, opts ...grpc.CallOption) (*{{.ServiceName | title}}Response, error)
	Get{{.ServiceName | title}}(ctx context.Context, in *Get{{.ServiceName | title}}Request, opts ...grpc.CallOption) (*{{.ServiceName | title}}Response, error)
	List{{.ServiceName | title}}s(ctx context.Context, in *List{{.ServiceName | title}}sRequest, opts ...grpc.CallOption) (*List{{.ServiceName | title}}sResponse, error)
	Update{{.ServiceName | title}}(ctx context.Context, in *Update{{.ServiceName | title}}Request, opts ...grpc.CallOption) (*{{.ServiceName | title}}Response, error)
	Delete{{.ServiceName | title}}(ctx context.Context, in *Delete{{.ServiceName | title}}Request, opts ...grpc.CallOption) (*Empty, error)
}`

const httpGoTemplate = `// Code generated by sunny-go. DO NOT EDIT.

package {{.ServiceName}}

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/gorilla/mux"
)

// {{.ServiceName | title}}ServiceHTTPServer is the server API for {{.ServiceName | title}}Service service over HTTP.
type {{.ServiceName | title}}ServiceHTTPServer interface {
	Create{{.ServiceName | title}}(context.Context, *Create{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	Get{{.ServiceName | title}}(context.Context, *Get{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	List{{.ServiceName | title}}s(context.Context, *List{{.ServiceName | title}}sRequest) (*List{{.ServiceName | title}}sResponse, error)
	Update{{.ServiceName | title}}(context.Context, *Update{{.ServiceName | title}}Request) (*{{.ServiceName | title}}Response, error)
	Delete{{.ServiceName | title}}(context.Context, *Delete{{.ServiceName | title}}Request) (*Empty, error)
}

// Register{{.ServiceName | title}}ServiceHTTPServer registers the http handlers for service {{.ServiceName | title}}Service.
func Register{{.ServiceName | title}}ServiceHTTPServer(mux *mux.Router, srv {{.ServiceName | title}}ServiceHTTPServer) {
	mux.HandleFunc("/api/v1/{{.ServiceName}}s", _{{.ServiceName | title}}Service_Create{{.ServiceName | title}}_HTTP_Handler(srv)).Methods("POST")
	mux.HandleFunc("/api/v1/{{.ServiceName}}s/{id}", _{{.ServiceName | title}}Service_Get{{.ServiceName | title}}_HTTP_Handler(srv)).Methods("GET")
	mux.HandleFunc("/api/v1/{{.ServiceName}}s", _{{.ServiceName | title}}Service_List{{.ServiceName | title}}s_HTTP_Handler(srv)).Methods("GET")
	mux.HandleFunc("/api/v1/{{.ServiceName}}s/{id}", _{{.ServiceName | title}}Service_Update{{.ServiceName | title}}_HTTP_Handler(srv)).Methods("PUT")
	mux.HandleFunc("/api/v1/{{.ServiceName}}s/{id}", _{{.ServiceName | title}}Service_Delete{{.ServiceName | title}}_HTTP_Handler(srv)).Methods("DELETE")
}

func _{{.ServiceName | title}}Service_Create{{.ServiceName | title}}_HTTP_Handler(srv {{.ServiceName | title}}ServiceHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req Create{{.ServiceName | title}}Request
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		resp, err := srv.Create{{.ServiceName | title}}(r.Context(), &req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func _{{.ServiceName | title}}Service_Get{{.ServiceName | title}}_HTTP_Handler(srv {{.ServiceName | title}}ServiceHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		req := Get{{.ServiceName | title}}Request{Id: vars["id"]}
		resp, err := srv.Get{{.ServiceName | title}}(r.Context(), &req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func _{{.ServiceName | title}}Service_List{{.ServiceName | title}}s_HTTP_Handler(srv {{.ServiceName | title}}ServiceHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req List{{.ServiceName | title}}sRequest
		if page := r.URL.Query().Get("page"); page != "" {
			if p, err := strconv.ParseInt(page, 10, 32); err == nil {
				req.Page = int32(p)
			}
		}
		if pageSize := r.URL.Query().Get("page_size"); pageSize != "" {
			if ps, err := strconv.ParseInt(pageSize, 10, 32); err == nil {
				req.PageSize = int32(ps)
			}
		}
		resp, err := srv.List{{.ServiceName | title}}s(r.Context(), &req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func _{{.ServiceName | title}}Service_Update{{.ServiceName | title}}_HTTP_Handler(srv {{.ServiceName | title}}ServiceHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		var req Update{{.ServiceName | title}}Request
		req.Id = vars["id"]
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		resp, err := srv.Update{{.ServiceName | title}}(r.Context(), &req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func _{{.ServiceName | title}}Service_Delete{{.ServiceName | title}}_HTTP_Handler(srv {{.ServiceName | title}}ServiceHTTPServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		req := Delete{{.ServiceName | title}}Request{Id: vars["id"]}
		resp, err := srv.Delete{{.ServiceName | title}}(r.Context(), &req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}`
