package wiregen_test

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/wahyurudiyan/sunny-go/internal/codegen/proto"
	"github.com/wahyurudiyan/sunny-go/internal/codegen/wiregen"
)

var _ = Describe("Generate", func() {
	var (
		protoDir string
		destDir  string
	)

	BeforeEach(func() {
		root, err := os.MkdirTemp("", "sgo-wiregen-test-*")
		Expect(err).NotTo(HaveOccurred())
		DeferCleanup(func() { Expect(os.RemoveAll(root)).To(Succeed()) })

		protoDir = filepath.Join(root, "contract", "pb")
		destDir = filepath.Join(root, "contract", "gen")
		Expect(os.MkdirAll(protoDir, 0755)).To(Succeed())

		Expect(proto.GenerateStub(protoDir, "user", "demo")).To(Succeed())
	})

	It("writes real protoc-gen-go and protoc-gen-go-grpc output", func() {
		fd, err := proto.Compile(protoDir, "user.proto")
		Expect(err).NotTo(HaveOccurred())

		Expect(wiregen.Generate(fd, destDir)).To(Succeed())

		pbGo, err := os.ReadFile(filepath.Join(destDir, "user.pb.go"))
		Expect(err).NotTo(HaveOccurred())
		Expect(string(pbGo)).To(ContainSubstring("Code generated by protoc-gen-go"))
		Expect(string(pbGo)).To(ContainSubstring("type User struct"))
		Expect(string(pbGo)).To(ContainSubstring("func (x *User) GetId() string"))

		grpcGo, err := os.ReadFile(filepath.Join(destDir, "user_grpc.pb.go"))
		Expect(err).NotTo(HaveOccurred())
		Expect(string(grpcGo)).To(ContainSubstring("Code generated by protoc-gen-go-grpc"))
		Expect(string(grpcGo)).To(ContainSubstring("UserServiceServer"))
	})
})
